Algoritmo "Atividade3"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Rafael]
// Descrição   : É uma mensagem de apresentação!
// Autor(a)    : Kauã Guilherme Almeida Melo
// Data atual  : 17/03/2026

//Exercício 3 - Crie um Algoritmo que exiba uma mensagem de apresentação: Olá! Meu nome é [seu nome] e estou aprendendo Algoritmo.

Var
  nome: caractere


Inicio
nome <- "Kaua "
escreva ("Olá, meu nome é : ",nome , "e estou aprendendo algoritmo")


Fimalgoritmo